src/main/urls.py
#/*
# * Copyright (c) Django Software Foundation and individual contributors.
# * All rights reserved.
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     1. Redistributions of source code must retain the above copyright
# *        notice, this list of conditions and the following disclaimer.
# *
# *     2. Redistributions in binary form must reproduce the above copyright
# *        notice, this list of conditions and the following disclaimer in the
# *        documentation and/or other materials provided with the distribution.
# *
# *     3. Neither the name of Django nor the names of its contributors may be
# *        used to endorse or promote products derived from this software
# *        without specific prior written permission.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# * POSSIBILITY OF SUCH DAMAGE.
# */

"""main URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("planning.urls")),
]

src/planning/urls.py
#/*
# * Copyright © 2018, 2019 Maël A
# *
# * This file is part of CLEP, a leaves scheduler web app.
# *
# * CLEP is free software: you can redistribute it and/or modify
# * it under the terms of the GNU Affero General Public License as
# * published by the Free Software Foundation, either version 3 of the
# * License, or (at your option) any later version.
# *
# * CLEP is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU Affero General Public License for more details.
# *
# * You should have received a copy of the GNU Affero General Public License
# * along with CLEP.  If not, see <https://www.gnu.org/licenses/>.
# */
#
#/*
# * This file and CLEP copy code from and use the Django web framework which is
# * distributed under the following license:
# *
# *
# * Copyright (c) Django Software Foundation and individual contributors.
# * All rights reserved.
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are met:
# *
# *     1. Redistributions of source code must retain the above copyright
# *        notice, this list of conditions and the following disclaimer.
# *
# *     2. Redistributions in binary form must reproduce the above copyright
# *        notice, this list of conditions and the following disclaimer in the
# *        documentation and/or other materials provided with the distribution.
# *
# *     3. Neither the name of Django nor the names of its contributors may be
# *        used to endorse or promote products derived from this software
# *        without specific prior written permission.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# * POSSIBILITY OF SUCH DAMAGE.
# */

from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = "planning"
urlpatterns = [
    path("", views.index, name="index"),
    path("accounts/login/", views.login, name="login"),
    path("accounts/logout/", views.logout, name="logout"),
    path("accounts/password_change/", views.change_password,
                                                    name="password_change"),
    path("accounts/password_change/done/", views.password_change_done,
                                                name="password_change_done"),
    path("calendar/<int:year>/<int:month>/", views.calendar, name="calendar"),
    path("calendar/history/", views.calendar_history, name="calendar_history"),
    path("leaverequest/", views.leave_request, name="leaverequest"),
    path("jsi18n/", JavaScriptCatalog.as_view(
                            packages=["django.contrib.admin"]), name="jsi18n"),
    path("requestslist/", views.requests_list, name="requestslist"),
    path("requestslistbackend/", views.requests_list_backend,
                                                    name="requestslistbackend"),
    path("modifyrequest/<int:request_id>/",
                                    views.modify_request, name="modifyrequest"),
    path("adminmodifyrequest/<int:request_id>/",
                        views.admin_modify_request, name="adminmodifyrequest"),
    path("adminmodifynonattendance/<int:request_id>/",
            views.admin_modify_nonattendance, name="adminmodifynonattendance"),
    path("adminrequestslist/", views.admin_requests_list,
                                                    name="adminrequestslist"),
    path("adminrequestslistbackend/", views.admin_requests_list_backend,
                                            name="adminrequestslistbackend"),
    path("addnonattendance/", views.add_nonattendance, name="addnonattendance"),
    path("nonattendanceslist/", views.nonattendances_list,
                                                    name="nonattendanceslist"),
    path("nonattendanceslistbackend/", views.nonattendances_list_backend,
                                            name="nonattendanceslistbackend"),
    path("report/", views.report, name="report"),
    path("adminreport/", views.admin_report, name="adminreport"),
    path("setoncallweekemployee/<int:year>/<int:week_number>/",
                views.set_oncall_week_employee, name="setoncallweekemployee"),
    path("selectoncallweek/", views.select_oncall_week,
                                                    name="selectoncallweek"),
    path("placeregularna/", views.place_regular_na, name="placeregularna"),
    path("placeemployeeregularna/", views.place_employee_regular_na,
                                                name="placeemployeeregularna"),
    path("addleaverequest/", views.add_leave_request, name="addleaverequest"),
    path("legalnotices/", views.legalnotices, name="legalnotices")
]

src/planning/templates/planning/base.html
<!--
/*
 * Copyright © 2018 Maël A
 *
 * This file is part of CLEP, a leaves scheduler web app.
 *
 * CLEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CLEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CLEP.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * This file and CLEP copy code from and use the Django web framework which is
 * distributed under the following license:
 *
 *
 * Copyright (c) Django Software Foundation and individual contributors.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice,
 *        this list of conditions and the following disclaimer.
 *
 *     2. Redistributions in binary form must reproduce the above copyright
 *        notice, this list of conditions and the following disclaimer in the
 *        documentation and/or other materials provided with the distribution.
 *
 *     3. Neither the name of Django nor the names of its contributors may be
 *        used to endorse or promote products derived from this software without
 *        specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
-->

{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% static "planning/footer.css" %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}" />
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}" />{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        <div id="user-tools">
            {% if user.is_authenticated %}
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
	    {% endif %}
            {% block userlinks %}
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}">Administration</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
		{% if user.has_usable_password %}
		<a href="{% url 'planning:password_change' %}">{% trans 'Change password' %}</a> /
		{% endif %}
                <a href="{% url 'planning:logout' %}">{% trans 'Log out' %}</a>
		{% else %}
                <a href="{% url 'planning:login' %}">Connexion</a>
		{% endif %}
            {% endblock %}
        </div>
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'planning:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

{% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

<div id="legalfooter">
	<a style="margin-right: 12px;" href="{% url 'planning:legalnotices' %}">MENTIONS LÉGALES</a>
	<a style="margin-left: 12px;" href="https://bitbucket.org/DarkSino/clep/src/v1.3/">CODE SOURCE</a>
</div>

</body>
</html>

src/planning/templates/planning/calendar.html
{% extends "planning/base_site.html" %}
{% comment %}
/*
 * Copyright © 2018 Maël A
 *
 * This file is part of CLEP, a leaves scheduler web app.
 *
 * CLEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CLEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CLEP.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * This file and CLEP copy code from and use the Django web framework which is
 * distributed under the following license:
 *
 *
 * Copyright (c) Django Software Foundation and individual contributors.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice,
 *        this list of conditions and the following disclaimer.
 *
 *     2. Redistributions in binary form must reproduce the above copyright
 *        notice, this list of conditions and the following disclaimer in the
 *        documentation and/or other materials provided with the distribution.
 *
 *     3. Neither the name of Django nor the names of its contributors may be
 *        used to endorse or promote products derived from this software without
 *        specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
{% endcomment %}

{% load static %}
{% load index %}
{% load add_request_perm %}
{% load i18n %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "planning/calendar.css" %}" />
{% endblock %}

{% block breadcrumbs %}
{% if not is_index %}
<div class="breadcrumbs">
<a href="{% url 'planning:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}</div>
{% endif %}
{% endblock %}

{% block pretitle %}
{% if user.is_authenticated %}
<div class="module">
<table>
	<caption>Actions</caption>
	<tr>
		<th scope="row"><a href="{% url "planning:leaverequest" %}">Demander des congés</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th scope="row"><a href="{% url "planning:requestslist" %}">Mes demandes de congés</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th scope="row"><a href="{% url "planning:report" %}">Mes statistiques</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% if perms.planning or user|has_add_request_perm %}
	<tr>
		<th scope="row"><a></a></th>
		<td class="menu-empty-row">&nbsp;</td>
		<td class="menu-empty-row">&nbsp;</td>
	</tr>
	{% endif %}
	{% if user|has_add_request_perm %}
	<tr>
		<th scope="row"><a href="{% url "planning:addleaverequest" %}">Ajouter une demande de congés</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.validate_request or perms.planning.invalidate_request or perms.planning.modify_request or perms.planning.delete_request or perms.planning.print_sheet %}
	<tr>
		<th scope="row"><a href="{% url "planning:adminrequestslist" %}">Toutes les demandes de congés</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.add_non_attendance %}
	<tr>
		<th scope="row"><a href="{% url "planning:addnonattendance" %}">Ajouter une absence</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.modify_non_attendance or perms.planning.delete_non_attendance %}
	<tr>
		<th scope="row"><a href="{% url "planning:nonattendanceslist" %}">Toutes les absences</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.view_statistics %}
	<tr>
		<th scope="row"><a href="{% url "planning:adminreport" %}">Statistiques des employés</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.assign_oncallweek %}
	<tr>
		<th scope="row"><a href="{% url "planning:selectoncallweek" %}">Attribuer astreinte</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
	{% if perms.planning.allocate_rtt_tp %}
	<tr>
		<th scope="row"><a href="{% url "planning:placeregularna" %}">Affecter les RTT et temps partiels de tous les employés</a><th>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th scope="row"><a href="{% url "planning:placeemployeeregularna" %}">Affecter les RTT et temps partiels d'un employé</a></th>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	{% endif %}
</table>
</div>
{% endif %}
{% endblock %}

{% block content %}
{% block object-tools %}
<ul class="object-tools">
	<li>
		<a href="{% url "planning:calendar_history" %}" class="historylink">Autre période</a>
	</li>
</ul>
{% endblock %}

<table id="leavestable">

	<colgroup
		{% if alternate_display %}
			span="2"
		{% else %}
			span="1"
		{% endif %}
	>
	</colgroup>
	<colgroup>
	{% for day in days %}
		{% if not alternate_display %}
			{% for daypart in dayparts %}
				<col class="daypart-columns">
			{% endfor %}
		{% else %}
			<col class="daypart-columns">
			<col class="daypart-columns">
		{% endif %}
	{% endfor %}
	</colgroup>

	<tr id="day-number-line">
		<th class="topleft-cell"
			{% if alternate_display %}
				colspan="2"
				{% if show_days_name %}
				rowspan="2"
				{% endif %}
			{% else %}
				{% if show_days_name %}
					{% if show_weeks_number %}
						rowspan="4"
					{% else %}
						rowspan="3"
					{% endif %}
				{% else %}
					{% if show_weeks_number %}
						rowspan="3"
					{% else %}
						rowspan="2"
					{% endif %}
				{% endif %}
			{% endif %}
		></th>

	{% for day in days %}
		<th
			{% if alternate_display %}
				colspan="2"
			{% else %}
				colspan="{{ daypart_count }}"
			{% endif %}
			class="day-number"
		>
			{{ forloop.counter }}
		</th>
	{% endfor %}
	</tr>

	{% if show_days_name %}
	<tr>
		{% for day in days %}
		<th
			{% if alternate_display %}
				colspan="2"
			{% else %}
				colspan="{{ daypart_count }}"
			{% endif %}
			class="day-number"
		>
			{{ day }}
		</th>
		{% endfor %}
	</tr>
	{% endif %}

{% if not alternate_display %}
	<tr>
	{% if show_weeks_number %}
		{% for week in weeks %}
			<th colspan="{{ week.length }}">{{ week.number }}</th>
		{% endfor %}
	{% endif %}
	</tr>

	<tr>
	{% for day in days %}
		{% for daypart in dayparts %}
			<th class="vertical-dayparts">{{ daypart }}</th>
		{% endfor %}
	{% endfor %}
	</tr>
{% endif %}

{% for user in users %}
	{% for i in rows_per_user %}
	<tr>
		{% if forloop.counter == 1 %}
		<th
			{% if alternate_display %}
				rowspan="{{ daypart_count }}"
			{% else %}
				rowspan="2"
			{% endif %}
			style="background-color: {{ user.color }}"
		>
			{{ user.last_name }} {{ user.first_name }}
		</th>
		{% endif %}

		{% if alternate_display %}
			<th>{{ dayparts|index:forloop.counter0 }}</th>
		{% endif %}

		{% include "planning/calendar_draw_day_interval.html" with days_intervals=user.days_intervals_set|index:forloop.counter0 counter=forloop.counter %}
	</tr>
	{% endfor %}
{% endfor %}

</table>

<br class="clear" />

<table style="margin: auto;">
<tr>
{% for na_type in nonattendances_types %}
		<td style="background-color: {{ na_type.color }};"></td>
		<th>{{ na_type.name }}</th>
{% endfor %}
</tr>
<tr>
{% for color in colors %}
		<td style="background-color: {{ color.value }};"></td>
		<th>{{ color.name }}</th>
{% endfor %}
		<td style="background: repeating-linear-gradient(
			45deg,
			#7a7a7a,
			#7a7a7a 5px,
			white 5px,
			white 10px)">
		</td>
		<th>provisoire</th>
		<td style="background-image: url('{% static "planning/vacation_bg.bmp" %}');"></td>
		<th>vacances scolaires</th>
</tr>
</table>

{% endblock %}